/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  whatapSidebar: [
    {
      type: 'category',
      label: '시작하기 전에',
      collapsible: false,
      collapsed: false,
      items: [ 
        'getting-started/support-env',
        'getting-started/create-account',
      ]
    },
    {
      type: 'category',
      label: '에이전트 적용하기',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'getting-started/install-agent',
      },
      items: [
        {
          type: 'category',
          label: '애플리케이션',
          link: {
            type: 'doc',
            id: 'getting-started/application-agent',
          },
          items: [
            'getting-started/java',
          ]
        },
        'getting-started/server-agent',
        'getting-started/database-agent',
        'getting-started/k8-agent',
        'getting-started/telegraf-agent',
        'getting-started/focus-agent',
        'getting-started/integration-agent',
      ]
    },
  ],
};

module.exports = sidebars;
