/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  releaseSidebar: [
    {
      type: 'category',
      label: '릴리스 노트',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'release-notes/release-notes'
      },
      items: [
        {
          type: 'category',
          label: 'Service 🚀',
          collapsible: true,
          collapsed: true,
          items: [
            'release-notes/service/service-1.92.0',
            'release-notes/service/service-1.90.0',
            'release-notes/service/service-1.88.0',
            'release-notes/service/service-1.86.0',
            'release-notes/service/service-1.84.0',
            'release-notes/service/service-1.82.0',
            'release-notes/service/service-1.80.0',
            'release-notes/service/service-1.78.0',
            'release-notes/service/service-1.76.0',
            'release-notes/service/service-1.74.0',
            'release-notes/service/service-previous',
          ]
        },
        {
          type: 'category',
          label: '에이전트',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Java',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/java/java-2.2.0',
                'release-notes/java/java-2.1.3',
                'release-notes/java/java-2.1.2',
                'release-notes/java/java-2.1.1',
                'release-notes/java/java-2.1.0',
                'release-notes/java/java-previous',
              ],
            },
            {
              type: 'category',
              label: 'PHP',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/php/php-2.5.4',
                'release-notes/php/php-2.5.3',
                'release-notes/php/php-2.5.2',
                'release-notes/php/php-2.5.1',
                'release-notes/php/php-2.5.0',
                'release-notes/php/php-2.4.1',
                'release-notes/php/php-2.4.0',
                'release-notes/php/php-2.3.3',
                'release-notes/php/php-previous',
              ],
            },
            {
              type: 'category',
              label: 'Python',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/python/python-1.2.4',
                'release-notes/python/python-1.2.1',
                'release-notes/python/python-1.2.0',
                'release-notes/python/python-1.1.6',
                'release-notes/python/python-previous',
              ],
            },
            {
              type: 'category',
              label: '.NET',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/dotnet/dotnet-2.0.4',
                'release-notes/dotnet/dotnet-2.0.3',
                'release-notes/dotnet/dotnet-2.0.2',
                'release-notes/dotnet/dotnet-2.0.1',
                'release-notes/dotnet/dotnet-2.0.0',
                'release-notes/dotnet/dotnet-previous',
              ],
            },
            {
              type: 'category',
              label: 'Golang',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/golang/golang-0.1.14',
                'release-notes/golang/golang-0.1.13',
                'release-notes/golang/golang-0.1.12',
                'release-notes/golang/golang-0.1.11',
                'release-notes/golang/golang-0.1.10',
                'release-notes/golang/golang-0.1.9',
                'release-notes/golang/golang-0.1.8',
                'release-notes/golang/golang-0.1.7',
                'release-notes/golang/golang-0.1.6',
                'release-notes/golang/golang-0.1.5',
              ],
            },
            {
              type: 'doc',
              label: 'Amazon ECS',
              id: 'release-notes/amazon-ecs/amazon-ecs-release-notes',
            },
            {
              type: 'category',
              label: 'Server 🚀',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/server/server-2.2.9',
                'release-notes/server/server-2.2.8',
                'release-notes/server/server-2.2.7',
                'release-notes/server/server-2.2.6',
                'release-notes/server/server-2.2.5',
                'release-notes/server/server-2.2.4',
                'release-notes/server/server-2.2.3',
                'release-notes/server/server-2.2.2',
                'release-notes/server/server-2.2.1',
                'release-notes/server/server-2.2.0',
                'release-notes/server/server-2.1.9',
                'release-notes/server/server-previous',
              ],
            },
            {
              type: 'category',
              label: 'DB',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/db/xos-1.1.3',
                'release-notes/db/xos-1.1.2',
                'release-notes/db/xos-1.1.1b',
                'release-notes/db/xos-1.1.1a',
                'release-notes/db/xos-1.1.1',
                'release-notes/db/xos-1.1.0b',
                'release-notes/db/xos-1.1.0a',
                'release-notes/db/xos-1.1.0',
                'release-notes/db/xos-previous',
              ],
            },
            {
              type: 'doc',
              label: 'Telegraf',
              id: 'release-notes/telegraf/telegraf-release-notes',
            },
            {
              type: 'doc',
              label: 'URL',
              id: 'release-notes/url/url-release-notes',
            },
            {
              type: 'doc',
              label: 'Focus',
              id: 'release-notes/focus/focus-release-notes',
            },
            {
              type: 'category',
              label: 'Kubernetes',
              collapsible: true,
              collapsed: true,
              items: [
                'release-notes/k8s/k8s-1.2.0',
                'release-notes/k8s/k8s-1.1.55',
                'release-notes/k8s/k8s-1.1.54',
                'release-notes/k8s/k8s-1.1.52',
                'release-notes/k8s/k8s-1.1.51',
                'release-notes/k8s/k8s-1.1.50',
                'release-notes/k8s/k8s-1.1.49',
                'release-notes/k8s/k8s-1.1.48',
                'release-notes/k8s/k8s-1.1.46',
                'release-notes/k8s/k8s-1.1.45',
                'release-notes/k8s/k8s-1.1.44',
                'release-notes/k8s/k8s-1.1.43',
                'release-notes/k8s/k8s-1.1.42',
                'release-notes/k8s/k8s-1.1.41',
                'release-notes/k8s/k8s-1.1.40',
              ],
            },
          ],
        },
      ]
    }
  ],
  manageSidebar: [
    {
      type: 'category',
      label: '관리 기능',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'manage'
      },
      items: [
        'account/account-manage',
        'account/mfa',
        'project/project-structure',
        'project/project',
        'project/group',
        'project/organization',
        'project/integrated-manage',
        'notification/rt-notification',
        'billing/billing',
        'maintenance/maintenance'
      ]
    }
  ],
  indexSidebar: [
    {
      type: 'category',
      label: '시작하기',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'index',
      },
      items: [
        'getting-started/whatap-overview',
        'getting-started/support-env',
        'getting-started/quick-guide',
        'navigation/main-ui-intro',
      ],
    },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'category',
      label: '제품별 문서 바로가기',
      collapsible: false,
      collapsed: false,
      className: 'shortcut',
      // link: {
      //   type: 'doc',
      //   id: 'shortcut',
      // },
      items: [
        {
          type: 'link',
          label: '애플리케이션',
          href: '../apm/application-intro',
          className: "_productlink"
        },
        {
          type: 'link',
          label: '서버',
          href: '../server/server-intro',
          className: "_productlink"
        },
        {
          type: 'link',
          label: '데이터베이스',
          href: '../db/db-monitoring-intro',
          className: "_productlink"
        },
        {
          type: 'link',
          label: '쿠버네티스',
          href: '../kubernetes/kubernetes-intro',
          className: "_productlink"
        },
        {
          type: 'link',
          label: '클라우드',
          href: '../ref-cloud/cloud',
          className: "_productlink"
        },
        {
          type: 'link',
          label: '로그',
          href: '../log/log-intro',
          className: "_productlink"
        },
        {
          type: 'link',
          label: 'URL',
          href: '../url/url-intro',
          className: "_productlink"
        },
        {
          type: 'doc',
          label: '확장 도구',
          id: 'extensions',
          className: "_productlink"
        },
        // {
        //   type: 'link',
        //   label: 'AWS Log',
        //   href: 'aws-log/install-aws-log'
        // },
        // {
        //   type: 'link',
        //   label: '인티그레이션',
        //   href: 'integration/integ-intro'
        // },
        // {
        //   type: 'link',
        //   label: 'Amazon ECS',
        //   href: 'amazon-ecs/amazon-ecs-intro' 
        // },
        // {
        //   type: 'link',
        //   label: 'Amazon Cloudwatch',
        //   href: 'amazon-cloudwatch/amazon-cloudwatch-install'
        // },
        // {
        //   type: 'link',
        //   label: 'Azure Monitor',
        //   href: 'azure/azure-monitor-install' 
        // },
        // {
        //   type: 'link',
        //   label: 'NCloud Monitoring',
        //   href: 'ncloud/ncloud-monitoring-install' 
        // },
        // {
        //   type: 'link',
        //   label: 'Oracle Cloud Monitor',
        //   href: 'oracle-cloud/oracle-cloud-monitor-install' 
        // },
        // {
        //   type: 'link',
        //   label: '브라우저(RUM)',
        //   href: 'rum/rum-intro'
        // },
        // {
        //   type: 'doc',
        //   label: 'Telegraf',
        //   id: 'telegraf/telegraf-intro',
        // },
        // {
        //   type: 'doc',
        //   label: 'Focus',
        //   id: 'focus/focus-intro',
        // },
      ],
    },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'link',
      label: '관리 기능',
      href: '../manage' 
    },
    {
      type: 'link',
      label: '참조 문서',
      href: '../reference' 
    },
    {
      type: 'link',
      label: '릴리스 노트',
      href: '../release-notes',
    },
  ],
  cloudSidebar: [
    {
      type: 'category',
      label: '클라우드 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'ref-cloud/cloud',
      },
      items: [
        {
          type: 'category',
          label: 'Amazon ECS',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'amazon-ecs/amazon-ecs-intro'
          },
          items: [
            'amazon-ecs/amazon-ecs-install',
            {
              type: 'category',
              label: '주요 메뉴 알아보기',
              collapsible: true,
              collapsed: false,
              link: {
                type: 'doc',
                id: 'amazon-ecs/learn-ecs-main-menu'
              },
              items: [
                'dashboard/ecs-dashboard',
                {
                  type: 'category',
                  label: 'Flex 보드',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'dashboard/ecs-flexboard',
                  },
                  items: [
                    'dashboard/ecs-flexboard-template',
                    'dashboard/ecs-flexboard-create',
                    'dashboard/ecs-flexboard-metric-widget',
                    'dashboard/ecs-flexboard-widget-manage',
                    'dashboard/ecs-flexboard-mode',
                    'dashboard/ecs-flexboard-share',
                  ]
                },
                'metrics/ecs-metrics-intro',
                {
                  type: 'category',
                  label: '알림 설정하기',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'notification/ecs-set-notice',
                  },
                  items: [
                    'notification/ecs-warning-and-history',
                    'notification/ecs-set-receive-event',
                    'notification/ecs-metric-warning-notice',
                  ]
                },
              ],
            }
          ]
        },
        {
          type: 'category',
          label: 'Amazon Cloudwatch',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'amazon-cloudwatch/amazon-cloudwatch-install'
          },
          items: [
            'amazon-cloudwatch/amazon-cloudwatch-install',
            {
              type: 'category',
              label: '주요 메뉴 알아보기',
              collapsible: true,
              collapsed: false,
              link: {
                type: 'doc',
                id: 'amazon-cloudwatch/learn-acw-main-menu'
              },
              items: [
                'dashboard/acw-dashboard',
                {
                  type: 'category',
                  label: 'Flex 보드',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'dashboard/acw-flexboard',
                  },
                  items: [
                    'dashboard/acw-flexboard-template',
                    'dashboard/acw-flexboard-create',
                    'dashboard/acw-flexboard-metric-widget',
                    'dashboard/acw-flexboard-widget-manage',
                    'dashboard/acw-flexboard-mode',
                    'dashboard/acw-flexboard-share',
                  ]
                },
                'metrics/aws-cloud-metrics-intro',
                {
                  type: 'category',
                  label: '알림 설정하기',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'notification/acw-set-notice',
                  },
                  items: [
                    'notification/acw-warning-and-history',
                    'notification/acw-set-receive-event',
                    'notification/acw-metric-warning-notice',
                  ]
                },
              ],
            }
          ]
        },
        {
          type: 'category',
          label: 'Azure Monitor',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'azure/azure-monitor-install'
          },
          items: [
            'azure/azure-monitor-install',
            {
              type: 'category',
              label: '주요 메뉴 알아보기',
              collapsible: true,
              collapsed: false,
              link: {
                type: 'doc',
                id: 'azure/learn-azure-main-menu'
              },
              items: [
                // 'dashboard/azure-dashboard',
                {
                  type: 'category',
                  label: 'Flex 보드',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'dashboard/azure-flexboard',
                  },
                  items: [
                    'dashboard/azure-flexboard-template',
                    'dashboard/azure-flexboard-create',
                    'dashboard/azure-flexboard-metric-widget',
                    'dashboard/azure-flexboard-widget-manage',
                    'dashboard/azure-flexboard-mode',
                    'dashboard/azure-flexboard-share',
                  ]
                },
                'metrics/azure-metrics-intro',
                {
                  type: 'category',
                  label: '알림 설정하기',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'notification/azure-set-notice',
                  },
                  items: [
                    'notification/azure-warning-and-history',
                    'notification/azure-set-receive-event',
                    'notification/azure-metric-warning-notice',
                  ]
                },
              ],
            }
          ]
        },
        {
          type: 'category',
          label: 'Naver Cloud Monitoring',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'ncloud/ncloud-monitoring-install'
          },
          items: [
            'ncloud/ncloud-monitoring-install',
            {
              type: 'category',
              label: '주요 메뉴 알아보기',
              collapsible: true,
              collapsed: false,
              link: {
                type: 'doc',
                id: 'ncloud/learn-ncloud-main-menu'
              },
              items: [
                // 'dashboard/ncloud-dashboard',
                {
                  type: 'category',
                  label: 'Flex 보드',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'dashboard/ncloud-flexboard',
                  },
                  items: [
                    'dashboard/ncloud-flexboard-template',
                    'dashboard/ncloud-flexboard-create',
                    'dashboard/ncloud-flexboard-metric-widget',
                    'dashboard/ncloud-flexboard-widget-manage',
                    'dashboard/ncloud-flexboard-mode',
                    'dashboard/ncloud-flexboard-share',
                  ]
                },
                'metrics/ncloud-metrics-intro',
                {
                  type: 'category',
                  label: '알림 설정하기',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'notification/ncloud-set-notice',
                  },
                  items: [
                    'notification/ncloud-warning-and-history',
                    'notification/ncloud-set-receive-event',
                    'notification/ncloud-metric-warning-notice',
                  ]
                },
              ],
            }
          ]
        },
        {
          type: 'category',
          label: 'Oracle Cloud Monitor',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'oracle-cloud/oracle-cloud-monitor-install'
          },
          items: [
            'oracle-cloud/oracle-cloud-monitor-install',
            {
              type: 'category',
              label: '주요 메뉴 알아보기',
              collapsible: true,
              collapsed: false,
              link: {
                type: 'doc',
                id: 'oracle-cloud/learn-oracle-main-menu'
              },
              items: [
                // 'dashboard/oracle-dashboard',
                {
                  type: 'category',
                  label: 'Flex 보드',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'dashboard/oracle-flexboard',
                  },
                  items: [
                    'dashboard/oracle-flexboard-template',
                    'dashboard/oracle-flexboard-create',
                    'dashboard/oracle-flexboard-metric-widget',
                    'dashboard/oracle-flexboard-widget-manage',
                    'dashboard/oracle-flexboard-mode',
                    'dashboard/oracle-flexboard-share',
                  ]
                },
                'metrics/oracle-metrics-intro',
                {
                  type: 'category',
                  label: '알림 설정하기',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'notification/oracle-set-notice',
                  },
                  items: [
                    'notification/oracle-warning-and-history',
                    'notification/oracle-set-receive-event',
                    'notification/oracle-metric-warning-notice',
                  ]
                },
              ],
            }
          ]
        },
      ],
    }
  ],
  referSidebar: [
    {
      type: 'category',
      label: '참조 문서',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'reference'
      },
      items: [
        'metrics/common-metrics-intro',
        {
          type: 'category',
          label: 'MXQL',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'mxql/mxql-overview',
          },
          items: [
            'mxql/mxql-guide',
            {
              type: 'category',
              label: '단계별 명령어 가이드',
              collapsible: true,
              collapsed: true,
              items: [
                'mxql/mxql-select',
                'mxql/mxql-loading',
                'mxql/mxql-calculate',
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Open API',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apidoc/openapi-intro',
          },
          items: [
            'apidoc/openapi-spec',
            {
              type: 'category',
              label: 'Open API 호출',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apidoc/openapi-call',
              },
              items: [
                'apidoc/openapi-call-meta',
                'apidoc/openapi-call-apm-spot',
                'apidoc/openapi-call-server-spot',
                'apidoc/openapi-call-apm-stat-data',
                'apidoc/openapi-call-server-stat-data',
                'apidoc/openapi-call-project-stat',
                'apidoc/openapi-call-long-stat',
                'apidoc/openapi-call-log',
                'apidoc/openapi-call-short-stat',
              ]
            },
            'apidoc/openapi-mxql'
,          ]
        },
        'glossary/glossary',
      ]
    }
  ],
  awslogSidebar: [
    {
      type: 'category',
      label: 'AWS Log 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'aws-log/aws-log-intro'
      },
      items: [
        'aws-log/install-aws-log',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'aws-log/learn-aws-log-main-menu'
          },
          items: [
            'log/aws-log-lt',
            'log/aws-log-exp',
            'log/aws-log-search',
            'log/aws-log-setting',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/aws-log-flexboard',
              },
              items: [
                'dashboard/aws-log-flexboard-template',
                'dashboard/aws-log-flexboard-create',
                'dashboard/aws-log-flexboard-metric-widget',
                'dashboard/aws-log-flexboard-widget-manage',
                'dashboard/aws-log-flexboard-mode',
                'dashboard/aws-log-flexboard-share',
              ]
            },
            'metrics/aws-log-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/aws-log-set-notice',
              },
              items: [
                'notification/aws-log-metric-warning-notice',
                'notification/aws-log-set-receive-event',               
              ]
            },
          ],
        }
      ]
    }
  ],
  pluginSidebar: [
    {
      type: 'category',
      label: '확장 도구',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'extensions'
      },
      items: [
        {
          type: 'category',
          label: 'Telegraf',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'telegraf/telegraf-intro'
          },
          items: [
            {
              type: 'category',
              label: '플러그인 설치와 활용',
              collapsible: true,
              collapsed: true,
              items: [
                'telegraf/install-tf-plugin',
                'telegraf/tf-plg-settings',
              ]
            },
            {
              type: 'category',
              label: '에이전트 설치와 활용',
              collapsible: true,
              collapsed: true,
              items: [
                'telegraf/tf-support',
                'telegraf/install-tf-agent',
                'telegraf/tf-troubleshooting',
                'telegraf/tf-settings',
                'telegraf/tf-manage',
              ]
            },
            'telegraf/tf-plugin-ex',
          ]
        },
        {
          type: 'category',
          label: 'Focus',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'focus/focus-intro'
          },
          items: [
            'focus/focus-supported-spec',
            'focus/install-focus',
            'focus/focus-settings',
            'focus/focus-usage',
          ]
        },
      ]
    }
  ],
  awsecsSidebar: [
    {
      type: 'category',
      label: 'Amazon ECS',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'amazon-ecs/amazon-ecs-intro'
      },
      items: [
        'amazon-ecs/amazon-ecs-install',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'amazon-ecs/learn-ecs-main-menu'
          },
          items: [
            'dashboard/ecs-dashboard',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/ecs-flexboard',
              },
              items: [
                'dashboard/ecs-flexboard-template',
                'dashboard/ecs-flexboard-create',
                'dashboard/ecs-flexboard-metric-widget',
                'dashboard/ecs-flexboard-widget-manage',
                'dashboard/ecs-flexboard-mode',
                'dashboard/ecs-flexboard-share',
              ]
            },
            'metrics/ecs-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/ecs-set-notice',
              },
              items: [
                'notification/ecs-warning-and-history',
                'notification/ecs-set-receive-event',
                'notification/ecs-metric-warning-notice',
              ]
            },
          ],
        }
      ]
    }
  ],
  amazoncloudwatchSidebar: [
    {
      type: 'category',
      label: 'Amazon Cloudwatch',
      collapsible: false,
      collapsed: false,
      // link: {
      //   type: 'doc',
      //   id: 'amazon-cloudwatch/amazon-cloudwatch-intro'
      // },
      items: [
        'amazon-cloudwatch/amazon-cloudwatch-install',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'amazon-cloudwatch/learn-acw-main-menu'
          },
          items: [
            'dashboard/acw-dashboard',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/acw-flexboard',
              },
              items: [
                'dashboard/acw-flexboard-template',
                'dashboard/acw-flexboard-create',
                'dashboard/acw-flexboard-metric-widget',
                'dashboard/acw-flexboard-widget-manage',
                'dashboard/acw-flexboard-mode',
                'dashboard/acw-flexboard-share',
              ]
            },
            'metrics/aws-cloud-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/acw-set-notice',
              },
              items: [
                'notification/acw-warning-and-history',
                'notification/acw-set-receive-event',
                'notification/acw-metric-warning-notice',
              ]
            },
          ],
        }
      ]
    }
  ],
  azuremonitorSidebar: [
    {
      type: 'category',
      label: 'Azure Monitor',
      collapsible: false,
      collapsed: false,
      // link: {
      //   type: 'doc',
      //   id: 'azure/azure-monitor-intro'
      // },
      items: [
        'azure/azure-monitor-install',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'azure/learn-azure-main-menu'
          },
          items: [
            // 'dashboard/azure-dashboard',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/azure-flexboard',
              },
              items: [
                'dashboard/azure-flexboard-template',
                'dashboard/azure-flexboard-create',
                'dashboard/azure-flexboard-metric-widget',
                'dashboard/azure-flexboard-widget-manage',
                'dashboard/azure-flexboard-mode',
                'dashboard/azure-flexboard-share',
              ]
            },
            'metrics/azure-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/azure-set-notice',
              },
              items: [
                'notification/azure-warning-and-history',
                'notification/azure-set-receive-event',
                'notification/azure-metric-warning-notice',
              ]
            },
          ],
        }
      ]
    }
  ],
  ncloudSidebar: [
    {
      type: 'category',
      label: 'Naver Cloud Monitoring',
      collapsible: false,
      collapsed: false,
      // link: {
      //   type: 'doc',
      //   id: 'amazon-cloudwatch/amazon-cloudwatch-intro'
      // },
      items: [
        'ncloud/ncloud-monitoring-install',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'ncloud/learn-ncloud-main-menu'
          },
          items: [
            // 'dashboard/ncloud-dashboard',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/ncloud-flexboard',
              },
              items: [
                'dashboard/ncloud-flexboard-template',
                'dashboard/ncloud-flexboard-create',
                'dashboard/ncloud-flexboard-metric-widget',
                'dashboard/ncloud-flexboard-widget-manage',
                'dashboard/ncloud-flexboard-mode',
                'dashboard/ncloud-flexboard-share',
              ]
            },
            'metrics/ncloud-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/ncloud-set-notice',
              },
              items: [
                'notification/ncloud-warning-and-history',
                'notification/ncloud-set-receive-event',
                'notification/ncloud-metric-warning-notice',
              ]
            },
          ],
        }
      ]
    }
  ],
  oracleSidebar: [
    {
      type: 'category',
      label: 'Oracle Cloud Monitor',
      collapsible: false,
      collapsed: false,
      // link: {
      //   type: 'doc',
      //   id: 'amazon-cloudwatch/amazon-cloudwatch-intro'
      // },
      items: [
        'oracle-cloud/oracle-cloud-monitor-install',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'oracle-cloud/learn-oracle-main-menu'
          },
          items: [
            // 'dashboard/oracle-dashboard',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/oracle-flexboard',
              },
              items: [
                'dashboard/oracle-flexboard-template',
                'dashboard/oracle-flexboard-create',
                'dashboard/oracle-flexboard-metric-widget',
                'dashboard/oracle-flexboard-widget-manage',
                'dashboard/oracle-flexboard-mode',
                'dashboard/oracle-flexboard-share',
              ]
            },
            'metrics/oracle-metrics-intro',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/oracle-set-notice',
              },
              items: [
                'notification/oracle-warning-and-history',
                'notification/oracle-set-receive-event',
                'notification/oracle-metric-warning-notice',
              ]
            },
          ],
        }
      ]
    }
  ],
  // integSidebar: [
  //   {
  //     type: 'category',
  //     label: '인티그레이션',
  //     collapsible: false,
  //     collapsed: false,
  //     link: {
  //       type: 'doc',
  //       id: 'integration/integ-intro'
  //     },
  //     items: [
  //       {
  //         type: 'category',
  //         label: '설치하기',
  //         collapsible: true,
  //         collapsed: true,
  //         link: {
  //           type: 'doc',
  //           id: 'integration/install-integ',
  //         },
  //         items: [
  //           'integration/items/integ-amazon-ecs',
  //           'integration/items/integ-amazon-cloudwatch',
  //           'integration/items/integ-azure-monitor',
  //           'integration/items/integ-ncloud-monitoring',
  //           'integration/items/integ-oracle-cloud-monitor',
  //         ],          
  //       },
  //       {
  //         type: 'category',
  //         label: '주요 메뉴 알아보기',
  //         collapsible: true,
  //         collapsed: false,
  //         link: {
  //           type: 'doc',
  //           id: 'integration/learn-integ-main-menu'
  //         },
  //         items: [
  //           // {
  //           //   type: 'category',
  //           //   label: '대시보드',
  //           //   collapsible: true,
  //           //   collapsed: true,
  //           //   link: {
  //           //     type: 'doc',
  //           //     id: 'dashboard/integ-dashboard-intro',
  //           //   },
  //           //   items: [
  //           //     'dashboard/integ-dashboard',
  //           //   ]
  //           // },
  //           'dashboard/integ-dashboard',
  //           {
  //             type: 'category',
  //             label: 'Flex 보드',
  //             collapsible: true,
  //             collapsed: true,
  //             link: {
  //               type: 'doc',
  //               id: 'dashboard/integ-flexboard',
  //             },
  //             items: [
  //               'dashboard/integ-flexboard-template',
  //               'dashboard/integ-flexboard-create',
  //               'dashboard/integ-flexboard-metric-widget',
  //               'dashboard/integ-flexboard-widget-manage',
  //               'dashboard/integ-flexboard-mode',
  //               'dashboard/integ-flexboard-share',
  //             ]
  //           },
  //           'metrics/integ-metrics-intro',
  //           {
  //             type: 'category',
  //             label: '알림 설정하기',
  //             collapsible: true,
  //             collapsed: true,
  //             link: {
  //               type: 'doc',
  //               id: 'notification/integ-set-notice',
  //             },
  //             items: [
  //               'notification/integ-warning-and-history',
  //               'notification/integ-set-receive-event',
  //               'notification/integ-metric-warning-notice',
  //             ]
  //           },
  //         ],
  //       }
  //     ]
  //   }
  // ],
  urlSidebar: [
    {
      type: 'category',
      label: 'URL 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'url/url-intro'
      },
      items: [
        'url/url-install',
        'url/url-event',
        'url/url-error-type',
        // {
        //   type: 'category',
        //   label: '주요 메뉴 알아보기',
        //   collapsible: true,
        //   collapsed: false,
        //   link: {
        //     type: 'doc',
        //     id: 'url/learn-url-main-menu'
        //   },
        //   items: [
        //     'dashboard/url-container-map',
        //   ],
        // }
      ]
    }
  ],
  rumsSidebar: [
    {
      type: 'category',
      label: '브라우저 모니터링(RUM)',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'rum/rum-intro'
      },
      items: [
        {
          type: 'category',
          label: '호환성 및 사전설정',
          collapsible: true,
          collapsed: true,
          items: [
            'rum/rum-browser-compatibility',
            'rum/rum-browser-preset',
          ],
        },
        'rum/rum-apply-agent',
        'rum/rum-before-starting',
        'rum/rum-dashboard',
        'rum/rum-pageload-dashboard',
        'rum/rum-resource-dashboard',
        'rum/rum-ajax-dashboard',
        'rum/rum-browser-error-dashboard',
		    'dashboard/dashboard-widget-setting',
        {
          type: 'category',
          label: 'Flex 보드',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'dashboard/rum-flex-board',
          },
          items: [
            'dashboard/rum-flexboard-template',
            'dashboard/rum-flexboard-create',
            'dashboard/rum-flexboard-metric-widget',
            'dashboard/rum-flexboard-widget-manage',
            'dashboard/rum-flexboard-mode',
            'dashboard/rum-flexboard-share',
          ],
        },
        'metrics/rum-metrics-intro',
        {
          type: 'category',
          label: '알림 설정하기',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'notification/rum-set-notics',
          },
          items: [
            'notification/rum-metric-warning-notice',
            'notification/rum-set-receive-event',
            'notification/rum-set-event-history'
          ],
        },
        'rum/rum-collect-data',
      ],
    }
  ],
  serverSidebar: [
    {
      type: 'category',
      label: '서버 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'server/server-intro',
      },
      items: [
        {
          type: 'doc',
          label: '지원 환경',
          id: 'server/server-spec',
        },
        {
          type: 'category',
          label: '설치하기',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'category',
              label: '에이전트 설치',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'server/server-install-agent'
              },
              items: [
                'server/server-os/server-linux',
                'server/server-os/server-windows',
                'server/server-os/server-other',
                'server/server-os/server-aws',
              ]
            },
            'server/after-install-server-agent'
          ],
        },
        {
          type: 'category',
          label: '설정하기',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'server/server-agent-settings',
          },
          items: [
            'server/server-agent-naming',
            'server/server-agent-network',
            'server/server-setting-rfv',
            'server/server-setting-pcounter',
            'server/server-setting-win32'
          ],
        },
        'server/server-adf',
        {
          type: 'category',
          label: '관리하기',
          collapsible: true,
          collapsed: true,
          items: [
            'server/server-agent-update',
            'server/server-agent-remove',
          ],
        },
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'server/learn-server-main-menu',
          },
          items: [
            // {
            //   type: 'category',
            //   label: '대시보드',
            //   collapsible: true,
            //   collapsed: true,
            //   link: {
            //     type: 'doc',
            //     id: 'dashboard/server-dashboard-intro'
            //   },
            //   items: [
            //     'dashboard/server-resourceboard',
            //     'dashboard/server-compoundeye',
            //   ]
            // },
            'dashboard/server-resourceboard',
            'dashboard/server-compoundeye',
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/server-flex-board',
              },
              items: [
                'dashboard/server-flexboard-template',
                'dashboard/server-flexboard-create',
                'dashboard/server-flexboard-metric-widget',
                'dashboard/server-flexboard-widget-manage',
                'dashboard/server-flexboard-mode',
                'dashboard/server-flexboard-share',
              ]
            },
            {
              type: 'category',
              label: '메트릭스',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'metrics/server-metrics-intro'
              },
              items: [
                'metrics/mtx-server',
              ]
            },
            {
              type: 'category',
              label: '분석하기',
              collapsible: true,
              collapsed: true,
              items: [
                'analysis/server-list',
                'analysis/server-detail',
                {
                  type: 'category',
                  label: '보고서',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'analysis/server-report-intro'
                  },
                  items: [
                    'analysis/server-report',
                    'analysis/server-integrated-report',
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/server-set-notice'
              },
              items: [
                'notification/server-warning-notice',
                'notification/server-metric-warning-notice',
                'notification/server-set-event-detect-anomal',
                'notification/server-set-event-log',
                'notification/server-set-receive-event',
                'notification/server-set-event-history',
                'notification/server-set-event-format',
              ]
            },
            {
              type: 'doc',
              label: '로그 모니터링',
              id: 'log/log-intro'
            },
            {
              type: 'link',
              label: 'Open API',
              href: '/apidoc/openapi-intro',
            }
          ],
        },
      ]  
    }
  ],
  kubeSidebar: [
    {
      type: 'category',
      label: '쿠버네티스 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'kubernetes/kubernetes-intro'
      },
      items: [
        {
          type: 'doc',
          label: '지원 환경',
          id: 'kubernetes/kubernetes-support'
        },
        {
          type: 'category',
          label: '설치하기',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'kubernetes/kubernetes-install',
          },
          items: [
            'kubernetes/install-master-node-agent',
            'kubernetes/install-application-agent',
            'kubernetes/create-name-space-project'
          ]
        },
        'kubernetes/kubernetes-agent-settings',
        {
          type: 'category',
          label: '관리하기',
          collapsible: true,
          collapsed: true,
          items: [
            'kubernetes/kubernetes-project',
            'kubernetes/kubernetes-agent',
            'kubernetes/kubernetes-update',
          ],
        },
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'kubernetes/learn-kubernetes-main-menu'
          },
          items: [
            {
              type: 'category',
              label: '컨테이너 맵',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/kubernetes-container-map',
              },
              items: [
                'dashboard/kubernetes-container-view',
                'dashboard/kubernetes-container-group',
                'dashboard/kubernetes-container-status',
              ]
            },
            {
              type: 'category',
              label: '컨테이너 맵 상세 보기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/kubernetes-container-map-detail-mode'
              },
              items: [
                'dashboard/kubernetes-container-map-metrics',
                'dashboard/kubernetes-container-map-trace',
                'dashboard/kubernetes-container-map-log',
                'dashboard/kubernetes-container-map-event',
              ],
            },
            {
              type: 'category',
              label: '리소스',
              collapsible: true,
              collapsed: true,
              items: [
                'resource/performance-summary',
                'resource/resource-node-list',
                'resource/resource-container-list',
                'resource/resource-container-volume',
                'resource/resource-master-meta',
                'resource/resource-namespace',
              ],
            },
            {
              type: 'category',
              label: '애플리케이션',
              collapsible: true,
              collapsed: true,
              items: [
                'kubernetes/application-service-dashboard',
                'kubernetes/kubernetes-hitmap',
                'kubernetes/kubernetes-multiservice-hitmap',
                'kubernetes/kubernetes-tx-profile',
                'kubernetes/application-daily-stat',
              ],
            },
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/k8s-flex-board',
              },
              items: [
                'dashboard/k8s-flexboard-template',
                'dashboard/k8s-flexboard-create',
                'dashboard/k8s-flexboard-metric-widget',
                'dashboard/k8s-flexboard-widget-manage',
                'dashboard/k8s-flexboard-mode',
                'dashboard/k8s-flexboard-share',
              ],
            },
            {
              type: 'category',
              label: '분석',
              collapsible: true,
              collapsed: true,
              items: [
                'metrics/kubernetes-metrics-intro',
                'analysis/kubernetes-analysis-msa',
                'analysis/kubernetes-analysis-stack',
                'analysis/kubernetes-pod-init-perform',
                'analysis/kubernetes-analysis-oom-container',
              ],
            },
            'kubernetes/kubernetes-log',
            'analysis/kubernetes-report',
            'analysis/kubernetes-integrated-report',
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/kubernetes-set-notice'
              },
              items: [
                'notification/k8s-warning-notice',
                'notification/k8s-metric-warning-notice',
                'notification/k8s-hitmap-notice',
                'notification/k8s-set-event-detect-anomal',
                'notification/k8s-set-event-log',
                'notification/k8s-set-receive-event',
                'notification/k8s-set-event-history',
              ],
            },
            {
              type: 'link',
              label: 'Open API',
              href: '/apidoc/openapi-intro'
            }
          ],
        }
      ]
    }
  ],
  dbSidebar: [
    {
      type: 'category',
      label: '데이터베이스 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'db/db-monitoring-intro'
      },
      items: [
        {
          type: 'doc',
          label: '지원 환경',
          id: 'db/db-monitoring-support',
        },
        {
          type: 'category',
          label: '설치하기',
          collapsible: true,
          collapsed: true,
          items: [
            'db/install-db-agent',
            'db/after-install-db-agent',
            'db/db-troubleshooting',
          ],
        },
        {
          type: 'category',
          label: '설정하기',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'db/db-agent-settings'
          },
          items: [
            {
              type: 'doc',
              label: '에이전트 네트워크 통신',
              id: 'db/db-agent-network',
            },
            {
              type: 'doc',
              label: '에이전트 이름 식별',
              id: 'db/db-agent-naming',
            },
            'db/db-agent-aws',
            'db/db-agent-data',
            'db/db-agent-xos-settings',
          ],
        },
        'db/db-agent-manage',
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'db/learn-db-main-menu'
          },
          items: [
            {
              type: 'category',
              label: '실시간 DB 성능 지표 확인',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/db-dashboard-intro'
              },
              items: [
                'dashboard/db-instance-list',
                'dashboard/db-instance-monitoring',
                'dashboard/db-multi-instance-monitoring',
                'dashboard/db-slow-query',
              ],
            },
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/db-flex-board',
              },
              items: [
                'dashboard/db-flexboard-template',
                'dashboard/db-flexboard-create',
                'dashboard/db-flexboard-metric-widget',
                'dashboard/db-flexboard-widget-manage',
                'dashboard/db-flexboard-mode',
                'dashboard/db-flexboard-share',
              ],
            },
            {
              type: 'category',
              label: '분석과 통계',
              collapsible: true,
              collapsed: true,
              // link: {
              //   type: 'doc',
              //   id: 'analysis/db-analysis-report-intro'
              // },
              items: [
                'analysis/db-analysis-function',
                'metrics/db-metrics-intro',
                'analysis/db-log-viewer',
                'analysis/db-stat',
                'analysis/db-report',
                'analysis/db-integrated-report',
              ]
            },
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/db-set-notics',
              },
              items: [
                'notification/db-warning-notice',
                'notification/db-metric-warning-notice',
                'notification/db-set-event-detect-anomal',
                'notification/db-set-receive-event',
                'notification/db-set-event-history',
                'notification/db-set-event-format',
              ],
            },
            {
              type: 'link',
              label: 'Open API',
              href: '/apidoc/openapi-intro'
            }
          ]
        }
      ],
    }
  ],
  apmSidebar: [
    {
      type: 'category',
      label: '애플리케이션 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'apm/application-intro',
      },
      items: [ 
        {
          type: 'category',
          label: 'JAVA 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/java-intro'
          },
          items: [
            {
              type: 'doc',
              label: '지원 환경',
              id: 'apm/java-supported-spec',
            },
            {
              type: 'category',
              label: '에이전트 설치',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/java',
              },
              items: [
                'apm/add-jvm-opt/tomcat',
                'apm/add-jvm-opt/jboss',
                'apm/add-jvm-opt/jeus',
                'apm/add-jvm-opt/weblogic',
                'apm/add-jvm-opt/websphere',
                'apm/add-jvm-opt/resin',
                'apm/add-jvm-opt/liberty',
                'apm/add-jvm-opt/jetty',
                'apm/add-jvm-opt/spring-boot',
                'apm/add-jvm-opt/play2',
                'apm/add-jvm-opt/ibm-bluemix',
                'apm/add-jvm-opt/elastic-beanstalk',
                'apm/add-jvm-opt/docker',
                'apm/add-jvm-opt/batch-app',
                'apm/add-jvm-opt/java-under-ver',
              ]
            },
            'apm/java-after-install-agent',
            {
              type: 'doc',
              label: '설치 문제 해결',
              id: 'apm/java-agent-troubleshooting'
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/java-set-agent',
              },
              items: [
                {
                  type: 'doc',
                  label: '에이전트 이름 식별',
                  id: 'apm/java-agent-name'
                },
                'apm/java-agent-control-function',
                {
                  type: 'doc',
                  label: '사용량 수집',
                  id: 'apm/java-agent-usage',
                },
                'apm/java-agent-network',
                'apm/java-agent-performance',
                {
                  type: 'doc',
                  label: '에이전트 로그',
                  id: 'apm/java-agent-log'
                },
                {
                  type: 'doc',
                  label: 'GC 로그 모니터링',
                  id: 'apm/java-agent-gc-log'
                },
                'apm/java-agent-transaction',
                'apm/java-agent-dbsql',
                'apm/java-agent-httpcapicall',
                {
                  type: 'category',
                  label: '에이전트 플러그인',
                  items: [
                    {
                      type: 'doc',
                      label: '스크립트 플러그인',
                      id: 'apm/java-script-plugin'
                    },
                    {
                      type: 'doc',
                      label: '위빙 플러그인',
                      id: 'apm/java-weaving-plugin'
                    },
                  ]
                },
                'apm/java-agent-number-of-user',
                'apm/java-agent-load-amount',
                'apm/java-agent-notification',
                'apm/java-agent-apdex',
                'apm/java-agent-static',
                'apm/java-agent-toplogy',
                'apm/java-agent-additional-option'
              ]
            },
            {
              type: 'category',
              label: '관리하기',
              items: [
                {
                  type: 'doc',
                  label: '에이전트 업데이트 및 삭제',
                  id: 'apm/java-update-agent'
                },
                'apm/java-msa-group',
                'apm/java-aes-256-encryption',
                'apm/java-scale-in-auto-delete',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'PHP 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/intro-php'
          },
          items: [
            {
              type: 'doc',
              id: 'apm/supported-spec-php'
            },
            {
              type: 'category',
              label: '에이전트 설치',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/php',
              },
              items: [
                'apm/php-os/redhat-centos',
                'apm/php-os/debian-ubuntu',
                'apm/php-os/amazon-linux',
                'apm/php-os/freebsd',
                'apm/php-os/alpine-linux',
                'apm/php-os/gcae',
                'apm/php-os/aws-eb'
              ]
            },
            {
              type: 'doc',
              label: '설치 점검',
              id: 'apm/php-install-check'
            },
            {
              type: 'doc',
              label: '설치 문제 해결',
              id: 'apm/php-agent-troubleshooting'
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/php-set-agent'
              },
              items: [               
                {
                  type: 'doc',
                  label: '에이전트 이름 식별',
                  id: 'apm/php-agent-name'
                },
                {
                  type: 'doc',
                  label: '에이전트 기능 제어',
                  id: 'apm/php-control-function'
                },
                {
                  type: 'doc',
                  label: '에이전트 통신 설정',
                  id: 'apm/php-agent-com'
                },
                {
                  type: 'doc',
                  label: '에이전트 성능 설정',
                  id: 'apm/php-agent-tx'
                },
                {
                  type: 'doc',
                  label: '에이전트 로그',
                  id: 'apm/php-agent-log'
                },
                {
                  type: 'doc',
                  label: '트랜잭션',
                  id: 'apm/php-transaction'
                },
                {
                  type: 'doc',
                  label: 'DB와 SQL',
                  id: 'apm/php-db-sql'
                },
                {
                  type: 'doc',
                  label: 'HTTPC와 API Call',
                  id: 'apm/php-httpc-api'
                },
                {
                  type: 'doc',
                  label: '사용자 수',
                  id: 'apm/php-collect-user'
                },
                {
                  type: 'doc',
                  label: 'Apdex',
                  id: 'apm/php-apdex'
                },
                {
                  type: 'doc',
                  label: '통계',
                  id: 'apm/php-stat'
                },
                {
                  type: 'doc',
                  label: '토폴로지 맵',
                  id: 'apm/php-tp-map'
                },
                {
                  type: 'doc',
                  label: '공유 메모리',
                  id: 'apm/php-shm'
                }
              ]
            },
            {
              type: 'category',
              label: '관리하기',
              items: [
                {
                  type: 'doc',
                  label: '패키지 업데이트',
                  id: 'apm/php-agent-update'
                },
                'apm/php-agent-temp-st',
                'apm/php-agent-remove'
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Node.js 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/nodejs-intro'
          },
          items: [
            {
              type: 'doc',
              label: '지원 환경',
              id: 'apm/nodejs-supported-spec'
            },
            {
              type: 'doc',
              label: '에이전트 설치',
              id: 'apm/nodejs-install-agent',
            },
            {
              type: 'doc',
              label: '설치 점검',
              id: 'apm/nodejs-after-install-agent',
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/nodejs-set-agent'
              },
              items: [
                {
                  type: 'doc',
                  label: '에이전트 이름 식별',
                  id: 'apm/nodejs-agent-name',
                },
                'apm/nodejs-agent-control-function',
                'apm/nodejs-agent-network',
                'apm/nodejs-agent-log',
                'apm/nodejs-agent-transaction',
                'apm/nodejs-agent-dbsql',
                'apm/nodejs-agent-httpcapicall',
                'apm/nodejs-agent-number-of-user',
                'apm/nodejs-agent-static',
                'apm/nodejs-agent-topology',
              ]
            },
            'apm/nodejs-agent-manage',
          ]
        },
        {
          type: 'category',
          label: 'Python 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/python-intro'
          },
          items: [
            {
              type: 'doc',
              label: '지원 환경',
              id: 'apm/python-supported-spec'
            },
            {
              type: 'doc',
              label: '에이전트 설치',
              id: 'apm/python-install-agent',
            },
            {
              type: 'doc',
              label: '설치 점검',
              id: 'apm/python-after-install-agent',
            },
            {
              type: 'doc',
              label: '설치 문제 해결',
              id: 'apm/python-agent-troubleshooting',
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/python-set-agent'
              },
              items: [
                {
                  type: 'doc',
                  label: '에이전트 이름 식별',
                  id: 'apm/python-agent-name'
                },
                {
                  type: 'doc',
                  label: '에이전트 기능 제어',
                  id: 'apm/python-control-function'
                },
                {
                  type: 'doc',
                  label: '에이전트 통신 설정',
                  id: 'apm/python-agent-com'
                },
                {
                  type: 'doc',
                  label: '에이전트 로그',
                  id: 'apm/python-agent-log'
                },
                {
                  type: 'doc',
                  label: '트랜잭션',
                  id: 'apm/python-transaction'
                },
                {
                  type: 'doc',
                  label: 'DB와 SQL',
                  id: 'apm/python-db-sql'
                },
                {
                  type: 'doc',
                  label: 'HTTPC와 API Call',
                  id: 'apm/python-httpc-api'
                },
                {
                  type: 'doc',
                  label: '사용자 수',
                  id: 'apm/python-collect-user'
                },
                {
                  type: 'doc',
                  label: '통계',
                  id: 'apm/python-stat'
                }
              ]
            },
            {
              type: 'doc',
              label: '고급 기능',
              id: 'apm/python-adf',
            },
            {
              type: 'category',
              label: '관리하기',
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  label: '에이전트 삭제',
                  id: 'apm/python-remove'
                },
                {
                  type: 'doc',
                  label: '패키지 관리',
                  id: 'apm/python-pkg'
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: '.NET 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/dotnet-intro'
          },
          items: [
            {
              type: 'doc',
              label: '지원 환경',
              id: 'apm/dotnet-supported-spec'
            },
            {
              type: 'doc',
              label: '에이전트 설치',
              id: 'apm/dotnet-install-agent',
            },
            {
              type: 'doc',
              label: '설치 점검',
              id: 'apm/dotnet-after-install'
            },
            {
              type: 'doc',
              label: '설치 문제 해결',
              id: 'apm/dotnet-agent-troubleshooting',
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/dotnet-set-agent'
              },
              items: [
                'apm/dotnet-agent-name',
                'apm/dotnet-control-function',
                'apm/dotnet-agent-network',
                'apm/dotnet-agent-performance',
                'apm/dotnet-agent-log',
                'apm/dotnet-agent-transaction',
                'apm/dotnet-agent-dbsql',
                'apm/dotnet-agent-httpcapicall',
                'apm/dotnet-agent-number-of-user',
                'apm/dotnet-agent-static',
                'apm/dotnet-agent-topology',
              ]
            },
            {
              type: 'doc',
              label: '관리하기',
              id: 'apm/dotnet-agent-manage'
            }
          ]
        },
        {
          type: 'category',
          label: 'Golang 모니터링',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'apm/golang-intro'
          },
          items: [
            {
              type: 'doc',
              label: '지원 환경',
              id: 'apm/golang-supported-spec'
            },
            {
              type: 'doc',
              label: '에이전트 설치',
              id: 'apm/golang-install-agent'
            },
            {
              type: 'doc',
              label: '설치 점검',
              id: 'apm/golang-after-install-agent'
            },
            {
              type: 'category',
              label: '설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'apm/golang-set-agent'
              },
              items: [
                'apm/golang-agent-name',
                'apm/golang-agent-transaction',
                'apm/golang-agent-dbsql',
                'apm/golang-agent-httpcall',
                'apm/golang-agent-method',
                'apm/golang-agent-number-of-user'
              ]
            },
            {
              type: 'doc',
              label: '관리하기',
              id: 'apm/golang-agent-manage'
            }
          ]
        },
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'apm/learn-apm-main-menu'
          },
          items: [
            {
              type: 'category',
              label: '대시보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/apm-dashboard-intro'
              },
              items: [
                'dashboard/apm-dashboard',
                'dashboard/dashboard-transactionmap',
                'dashboard/dashboard-active-transaction',
              ],
            },
            {
              type: 'category',
              label: 'Flex 보드',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'dashboard/flex-board',
              },
              items: [
                'dashboard/flexboard-template',
                'dashboard/flexboard-create',
                'dashboard/flexboard-metric-widget',
                'dashboard/flexboard-widget-manage',
                'dashboard/flexboard-mode',
                'dashboard/flexboard-share',
              ],
            },
            {
              type: 'category',
              label: '토폴로지',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'topology/apm-topology',
              },
              items: [
                'topology/topology-basic',
                'topology/topology-type',
                'topology/topology-add-function',
                'topology/topology-settings'
              ],
            },
            {
              type: 'category',
              label: '트랜잭션',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'track-transactions/track-transactions-intro'
              },
              items: [
                'track-transactions/trs-view',
                'track-transactions/trs-profile',
                'track-transactions/active-transactions',
                'track-transactions/collect-stacks',
                'track-transactions/trs-multi-trace',
                'track-transactions/trs-endpoint-setting',
              ]
            },
            {
              type: 'category',
              label: '메트릭스',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'metrics/metrics-intro'
              },
              items: [
                'metrics/metrics-app',
                'metrics/metrics-performance-counter',
              ]
            },
            {
              type: 'category',
              label: '분석하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'analysis/analysis-report-intro'
              },
              items: [
                'analysis/cube',
                'analysis/analysis-apm',
                'analysis/analysis-apm-trs',
                {
                  type: 'category',
                  label: '보고서',
                  collapsible: true,
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'analysis/report-intro'
                  },
                  items: [
                    'analysis/report-apm',
                    'analysis/integrated-report',
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: '알림 설정하기',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'notification/apm-set-notice',
              },
              items: [
                'notification/apm-warning-notice',
                'notification/metric-warning-notice',
                'notification/hitmap-notice',
                'notification/set-event-detect-anomal',
                'notification/set-event-log',
                'notification/set-receive-event',
                'notification/set-event-history',
                'notification/set-event-format',
              ],
            },
            {
              type: 'doc',
              label: '로그 모니터링',
              id: 'log/log-intro'
            },
            {
              type: 'link',
              label: 'Open API',
              href: '/apidoc/openapi-intro'
            }
          ]
        }
      ]
    }
  ],
  logSidebar: [
    {
      type: 'category',
      label: '로그 모니터링',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'log/log-intro',
      },
      items: [
        {
          type: 'category',
          label: '적용하기',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'log/log-function',
          },
          items: [
            'log/log-java',
            'log/log-php',
            'log/log-python',
            'log/log-server'
          ],
        },
        {
          type: 'category',
          label: '주요 메뉴 알아보기',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'doc',
            id: 'log/log-learn-main-menu',
          },
          items: [
            'log/log-lt',
            'log/log-exp',
            'log/log-search', 
            'log/log-setting',          
            'notification/log-alert'
          ],
        },
      ]  
    }
  ]  
};

module.exports = sidebars;
