import React, { useRef, useEffect } from "react";
import { TabulatorFull as Tabulator } from "tabulator-tables";
import  "tabulator-tables/dist/css/tabulator.min.css";
import Layout from '@theme/Layout';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import whatapLocale from '@site/src/components/ui-text/whatap-locale.json';
import styles from './styles.module.css';
import {translate} from '@docusaurus/Translate';

export default function App() {
  const { i18n: { currentLocale } } = useDocusaurusContext();

  const menuItem = (sid) => {
    let oText;
    try {
      oText = whatapLocale[sid][currentLocale];
    } catch (e) {
      console.log(e, sid);
    }
    return oText;
  };

  const instantList = menuItem("side_instanceList");
  const dbMonitoring = menuItem("side_dbMonitoring");
  const multiInstance = menuItem("side_multiInstance");
  const slowQueryLog = menuItem("side_slowQueryLog");
  const flexboard = menuItem("side_flexboard");
  const dbTrendComparison = menuItem("side_dbTrendComparison"); // 카운트 추이 비교
  const dbTrend = menuItem("side_dbTrend"); // 카운트 추이
  const dbLockTree = menuItem("side_dbLockTree"); // 락트리
  const deadLock = menuItem("side_deadLock"); // 데드락
  const sessionHistory = menuItem("side_sessionHistory"); // 세션 히스토리
  const dbWaitAnalysis = menuItem("side_dbWaitAnalysis"); // Wait 분석
  const dbSqlAnalysis = menuItem("side_dbSqlAnalysis"); // SQL 분석
  const dbObjectInfo = menuItem("side_dbObjectInfo"); // Top 오브젝트
  const dbTopSqlComparison = menuItem("side_dbTopSqlComparison"); // Top SQL 비교
  const dbParameter = menuItem("side_dbParameter"); // 데이터베이스 파라미터
  const metricsChart = menuItem("side_metricsChart"); // 메트릭스 차트
  const metricsSearch = menuItem("side_metricsSearch"); // 메트릭스 조회
  const metricsML = menuItem("side_metricsML"); // 메트릭스 이상 탐지
  const pqTree = menuItem("side_pqTree"); // 병렬 쿼리 트리
  const dbSqlStat = menuItem("side_dbSqlStat"); // SQL 통계
  const pgStat = menuItem("side_pgStat"); // PG SQL 통계
  const mysqlStat = menuItem("side_mysqlStat"); // MYSQL SQL 통계
  const tableInfo = menuItem("side_tableInfo"); // 테이블 사이즈 증감
  const dbProcedureStat = menuItem("side_dbProcedureStat"); // 프로시저 통계
  const dbSize = menuItem("side_dbSize"); // 데이터베이스 사이즈
  const tableSpace = menuItem("side_tableSpace"); // 테이블스페이스 사이즈
  const sga = menuItem("side_sga"); // SGA 사이즈
  const report = menuItem("side_report"); // 보고서
  const dbJobInfo = menuItem("side_dbJobInfo"); // Job 수행내역
  const dbBackupRecoveryHistory = menuItem("side_dbBackupRecoveryHistory"); // 백업/복구 내역
  const logTail = menuItem("side_logTail"); // 라이브 테일
  const logExplorer = menuItem("side_logExplorer"); // 로그 트랜드
  const logSearch = menuItem("side_logSearch"); // 로그 검색
  const logSetting = menuItem("side_logSetting"); // 로그 설정
  const eventSetting = menuItem("side_eventSetting"); // 이벤트 설정
  const eventNoti = menuItem("side_eventNoti"); // 이벤트 수신 설정
  const eventHistory = menuItem("side_eventHistory"); // 이벤트 기록
  const correlatedProjectManagement = menuItem("side_correlatedProjectManagement"); // 연계 프로젝트 관리
  const instanceDashboard = menuItem("TTL08442"); // 인스턴스 대시보드
  const linkedDbinfo = menuItem("TTL07860"); // 연계 데이터베이스 정보
  const dbCloudSetting = menuItem("side_dbCloudSetting"); // 클라우드 설정
  const dbScriptManager = menuItem("side_dbScriptManager"); // 스크립트 매니저

  const funcs = [
    {
      category: "Dashboard",
      function: instantList,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Dashboard",
      function: dbMonitoring,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Dashboard",
      function: multiInstance,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Dashboard",
      function: slowQueryLog,
      pgsql: true,
      pgsqlv1: true,
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: true,
      mysqlv1: true,
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: true,
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Dashboard",
      function: flexboard,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: dbTrendComparison,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: dbTrend,
      pgsql: "",
      pgsqlv1: true,
      oracle: "",
      oraclev1: true,
      oraclepro: "",
      mysql: "",
      mysqlv1: true,
      mssql: "",
      mssqlv1: true,
      tibero: true,
      cubrid: "",
      cubridv1: true,
      altibase: "",
      altibasev1: true,
      redis: "",
      redisv1: true,
      mongodb: "",
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: dbLockTree,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: deadLock,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: pqTree,
      pgsql: "",
      pgsqlv1: "",
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: true,
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: sessionHistory,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: dbWaitAnalysis,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: dbSqlAnalysis,
      pgsql: "",
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: dbObjectInfo,
      pgsql: true,
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: dbTopSqlComparison,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Analysis",
      function: dbParameter,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: metricsChart,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: metricsSearch,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Analysis",
      function: metricsML,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Stat/Report",
      function: dbSqlStat,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: pgStat,
      pgsql: true,
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: mysqlStat,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: true,
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: tableInfo,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: true,
      mysqlv1: true,
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: true,
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: dbProcedureStat,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: dbSize,
      pgsql: true,
      pgsqlv1: true,
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: true,
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Stat/Report",
      function: tableSpace,
      pgsql: "",
      pgsqlv1: "",
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: true,
      cubrid: "",
      cubridv1: "",
      altibase: true,
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: sga,
      pgsql: "",
      pgsqlv1: "",
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: "",
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: true,
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: report,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: dbJobInfo,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Stat/Report",
      function: dbBackupRecoveryHistory,
      pgsql: "",
      pgsqlv1: "",
      oracle: "",
      oraclev1: "",
      oraclepro: "",
      mysql: "",
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Log",
      function: logTail,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: "",
      altibase: true,
      altibasev1: "",
      redis: true,
      redisv1: "",
      mongodb: true,
      mongodbv1: "",
    },
    {
      category: "Log",
      function: logExplorer,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: "",
      altibase: true,
      altibasev1: "",
      redis: true,
      redisv1: "",
      mongodb: true,
      mongodbv1: "",
    },
    {
      category: "Log",
      function: logSearch,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: "",
      altibase: true,
      altibasev1: "",
      redis: true,
      redisv1: "",
      mongodb: true,
      mongodbv1: "",
    },
    {
      category: "Log",
      function: logSetting,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: true,
      mssqlv1: "",
      tibero: "",
      cubrid: true,
      cubridv1: "",
      altibase: true,
      altibasev1: "",
      redis: true,
      redisv1: "",
      mongodb: true,
      mongodbv1: "",
    },
    {
      category: "Alert",
      function: eventSetting,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Alert",
      function: eventNoti,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Alert",
      function: eventHistory,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Correlation analysis",
      function: correlatedProjectManagement,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Correlation analysis",
      function: `${instanceDashboard} (APM → DB)`,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: true,
      redisv1: true,
      mongodb: true,
      mongodbv1: true,
    },
    {
      category: "Correlation analysis",
      function: `${linkedDbinfo} with APM(java)`,
      pgsql: true,
      pgsqlv1: "",
      oracle: true,
      oraclev1: "",
      oraclepro: true,
      mysql: true,
      mysqlv1: "",
      mssql: "",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Management",
      function: dbCloudSetting,
      pgsql: "AWS CloudWatch\nAzure",
      pgsqlv1: "",
      oracle: "AWS CloudWatch",
      oraclev1: "",
      oraclepro: "",
      mysql: "AWS CloudWatch\nAzure",
      mysqlv1: "",
      mssql: "AWS CloudWatch",
      mssqlv1: "",
      tibero: "",
      cubrid: "",
      cubridv1: "",
      altibase: "",
      altibasev1: "",
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    },
    {
      category: "Labs",
      function: dbScriptManager,
      pgsql: true,
      pgsqlv1: true,
      oracle: true,
      oraclev1: true,
      oraclepro: true,
      mysql: true,
      mysqlv1: true,
      mssql: true,
      mssqlv1: true,
      tibero: true,
      cubrid: true,
      cubridv1: true,
      altibase: true,
      altibasev1: true,
      redis: "",
      redisv1: "",
      mongodb: "",
      mongodbv1: "",
    }
  ];

  const RenderTable = () => {
    const tableRef = useRef(null); // DOM 요소를 참조하기 위한 Ref

    useEffect(() => {
      // Tabulator 인스턴스를 생성
      new Tabulator(tableRef.current, {
        width: "100%", // 테이블 너비 설정
        height: "100%",
        autoResize: false,
        data: funcs, // 데이터
        layout: "fitDataFill", // 레이아웃
        groupBy: "category", // 그룹핑 필드
        headerHozAlign: "center",
        columns: [
          { title: "Functions", field: "function", hozAlign: "left", headerHozAlign: "center", headerVertical:false, headerSort: false, width:251, frozen:true },
          { 
            title: "PostgreSQL",
            columns: [
              { title: "V2", field: "pgsql", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
              { title: "V1", field: "pgsqlv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
            ]
          },
          { 
            title: "Oracle",
            columns: [
              { title: "V2", field: "oracle", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
              { title: "V1", field: "oraclev1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
              { title: "Pro", field: "oracle", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
            ]
          },
          {
            title: "MySQL",
            columns: [
              { title: "V2", field: "mysql", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
              { title: "V1", field: "mysqlv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
            ]
          },
          {
            title: "SQL Server V2",
            columns: [
              { title: "SQL Server V2", field: "mssql", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false, width:157, formatter: "adaptable" },
              { title: "SQL Server V1", field: "mssqlv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" }
            ]
          },
          { title: "Tibero", field: "tibero", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
          {
            title: "CUBRID",
            columns: [
              { title: "V2", field: "cubrid", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
              { title: "V1", field: "cubridv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" }
            ]
          },
          {
            title: "Altibase",
            columns: [
              { title: "V2", field: "altibase", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
              { title: "V1", field: "altibasev1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" }
            ]
          },
          {
            title: "Redis",
            columns: [
              { title: "V2", field: "redis", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
              { title: "V1", field: "redisv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" }
            ]
          },
          {
            title: "MongoDB",
            columns: [
              { title: "V2", field: "mongodb", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
              { title: "V1", field: "mongodbv1", hozAlign: "center", headerHozAlign: "center", headerVertical:false, headerSort: false,width:157, formatter: "adaptable" },
            ]
          },
        ],
      });
    }, []); // 컴포넌트가 마운트될 때 한 번 실행

    return <div ref={tableRef} id="example-table" />;
  };
  
  return (
    <Layout>
      <div className={styles.mainwrapper}>
        <h1 className={styles.title}>
          {translate({
              id: "pages.dbfunctions.title",
              message: "데이터베이스별 지원 기능 비교"
          })}
        </h1>
        <RenderTable />
      </div>
    </Layout>
  )
}
